# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonzo < Formula
  desc "Gonzo! The Go based TUI log analysis tool"
  homepage "https://github.com/control-theory/gonzo"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.2/gonzo-0.1.2-darwin-amd64.tar.gz"
      sha256 "b5e372617423f90da13e6ff46df342e66010de9506e86a004368aab372320608"

      def install
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.2/gonzo-0.1.2-darwin-arm64.tar.gz"
      sha256 "790162a7074546acf81769adf1e1ae3296d2cf6d9c9098cb15637ccac16d6951"

      def install
        bin.install "gonzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.2/gonzo-0.1.2-linux-amd64.tar.gz"
      sha256 "7e6efb7930439d4d4b95090167760c83d8ef982f393481e304a436b0c8c96b92"
      def install
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.2/gonzo-0.1.2-linux-arm64.tar.gz"
      sha256 "816229f7d19b4d50e0244e1172b763e7e179d36271fc9f629d70ee7e084601bf"
      def install
        bin.install "gonzo"
      end
    end
  end

  test do
    system "#{bin}/gonzo", "--version"
  end
end
