# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonzo < Formula
  desc "Gonzo! The Go based TUI log analysis tool"
  homepage "https://github.com/control-theory/gonzo"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.1/gonzo-0.4.1-darwin-amd64.tar.gz"
      sha256 "bc23591f9617953eca13c47a56462297ac7e623ea1dcba5a2bd39029d82105d3"

      define_method(:install) do
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.1/gonzo-0.4.1-darwin-arm64.tar.gz"
      sha256 "ccf951cadca56a0f316c69f5758efa1bc993ef2edd4fce3b18d5d136536c8f38"

      define_method(:install) do
        bin.install "gonzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.1/gonzo-0.4.1-linux-amd64.tar.gz"
      sha256 "fb0a6d66677f10e31f8b510692ac62eb50784000d5f3557a0c3568f604748a2c"
      define_method(:install) do
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.1/gonzo-0.4.1-linux-arm64.tar.gz"
      sha256 "35d5bd0f0e52a9f76c65a3073bd75c7fdff5aa8ddb064bda3fa503dcc827bed5"
      define_method(:install) do
        bin.install "gonzo"
      end
    end
  end

  test do
    system "#{bin}/gonzo", "--version"
  end
end
