# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonzo < Formula
  desc "Gonzo! The Go based TUI log analysis tool"
  homepage "https://github.com/control-theory/gonzo"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.7/gonzo-0.1.7-darwin-amd64.tar.gz"
      sha256 "5609c175b4619c2fdb43504b18fa532078bed8af9bac5c5a09d059f9e5b40423"

      def install
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.7/gonzo-0.1.7-darwin-arm64.tar.gz"
      sha256 "da1ec7dc0e8c0c1e7d57e63fc906552c42f13d7cc9aa5fdde052833f8496c47f"

      def install
        bin.install "gonzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.7/gonzo-0.1.7-linux-amd64.tar.gz"
      sha256 "35895ee61264b48ed0a083e09338f8571b79686a544efaf93466c0e86d837e37"
      def install
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.1.7/gonzo-0.1.7-linux-arm64.tar.gz"
      sha256 "299054a297c8dc464038c3cb4120b37d4a0ea7888ff6a1c8eba68dbca81bd377"
      def install
        bin.install "gonzo"
      end
    end
  end

  test do
    system "#{bin}/gonzo", "--version"
  end
end
