# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonzo < Formula
  desc "Gonzo! The Go based TUI log analysis tool"
  homepage "https://github.com/control-theory/gonzo"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.2/gonzo-0.4.2-darwin-amd64.tar.gz"
      sha256 "372cd45549760b7fd366557dfe7f62c71e847d470192c12034c859a2c7d65022"

      define_method(:install) do
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.2/gonzo-0.4.2-darwin-arm64.tar.gz"
      sha256 "b2da3f43a5e8d601adbade1305487537fde7d1b8538d40fa3ba8c310b857af4c"

      define_method(:install) do
        bin.install "gonzo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.2/gonzo-0.4.2-linux-amd64.tar.gz"
      sha256 "ed2e78baf929bbc385f7495fdd0c43892f17f13cf3f2600d91857b9ce2ed8e23"
      define_method(:install) do
        bin.install "gonzo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/gonzo/releases/download/v0.4.2/gonzo-0.4.2-linux-arm64.tar.gz"
      sha256 "c142ed39f9a01db794700e096b46638abe5168e9dad65f5c11cf4e217d1fb0aa"
      define_method(:install) do
        bin.install "gonzo"
      end
    end
  end

  test do
    system "#{bin}/gonzo", "--version"
  end
end
